### ISSUE TITLE
What are the python. keras and tensorflow versions?

### ISSUE THREAD

**Issue by Ilthizam** [monjurulkarim/vehicle_distance#1]
Using TensorFlow backend.
2021-08-04 07:11:40.723688: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-08-04 07:11:40.723843: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-08-04 07:11:40.723867: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "vehicle_distance/yolo_video.py", line 5, in <module>
    from yolo import YOLO, detect_video
  File "/content/vehicle_distance/yolo.py", line 10, in <module>
    from keras import backend as K
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py", line 26, in <module>
    from .vis_utils import model_to_dot
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/vis_utils.py", line 7, in <module>
    from ..models import Model
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 10, in <module>
    from .engine.input_layer import Input
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/__init__.py", line 3, in <module>
    from .input_layer import Input
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_layer.py", line 7, in <module>
    from .base_layer import Layer
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 12, in <module>
    from .. import initializers
  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 49, in populate_deserializable_objects
    LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
AttributeError: module 'tensorflow_core.compat.v2' has no attribute '__internal__'

**Comment by monjurulkarim** [comment]
Hello,
Python 3.5.2
Keras 2.1.5
tensorflow 1.6.0.

You may try changing your TensorFlow version.  Thank you.

**Comment by Ilthizam** [comment]
@monjurulkarim can you provide the environment details with all other dependencies? 


detecting images
(416, 416, 3)
Found 3 boxes for img
Traceback (most recent call last):
  File "yolo_video.py", line 101, in <module>
    detect_video(YOLO(**vars(FLAGS)), FLAGS.input, FLAGS.output)
  File "F:\Research\vehicle_distance-master\yolo.py", line 277, in detect_video
    image = yolo.detect_image(image)
  File "F:\Research\vehicle_distance-master\yolo.py", line 134, in detect_image
    size=np.floor(3e-2 * image.size[1] + 0.5).astype('int32'))
  File "C:\Users\ASUS\anaconda3\envs\yolo3\lib\site-packages\PIL\ImageFont.py", line 655, in truetype
    return freetype(font)
  File "C:\Users\ASUS\anaconda3\envs\yolo3\lib\site-packages\PIL\ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\ASUS\anaconda3\envs\yolo3\lib\site-packages\PIL\ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

**Comment by monjurulkarim** [comment]
Looks like you don't have the font. You may change the font in
https://github.com/monjurulkarim/vehicle_distance/blob/1981d65ff1c192bff3546834febda856aac049cf/yolo.py#L133

One probable solution is to use the default font.
![image](https://user-images.githubusercontent.com/40798690/129106201-e11ad19a-86d0-45b8-bd60-dd05d31ac5c1.png)

if it does not work you may try any other font.

**Comment by monjurulkarim** [comment]
@Ilthizam 
Hello, for your information, "yolo.py" file has been updated to address your issue. Please, download the latest commit and retry to run the code. If you face further difficulties please let me know.
